version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_envbox
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./files/nginxcfg/default.conf:/go/files/nginxcfg/default.conf:shared
    environment:
      - GO_ENV=development

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
    volumes:
      - ./files/nginxcfg/default.conf:/etc/nginx/conf.d/default.conf:shared
    depends_on:
      - app
    container_name: nginx-reverse-proxy
